### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by richardpon** [TeamTravelJournal/AndroidTravelJournalApp#193]
I was in map -> detail and was navigating back to map and then back to listview

06-23 22:09:44.626  10223-10223/com.mycompany.traveljournal E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mycompany.traveljournal, PID: 10223
    java.lang.NullPointerException: Attempt to invoke virtual method 'double com.mycompany.traveljournal.models.Post.getLatitude()' on a null object reference
            at com.mycompany.traveljournal.mapscreen.MapActivity$5.run(MapActivity.java:448)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by richardpon** [comment]
in the map view, I was long clicking to show the "connect the dots" and was scrolling.  This is the first time I've seen this crash...

**Comment by esrako** [comment]
Will look into details later.
Currently doing the animation and moving map doesn't go well together, as moving deletes post/pin objects and animation tries to access those deleted objects.

**Comment by richardpon** [comment]
Let's just not fix this one, as we can just keep the map stationary during the demo
