### ISSUE TITLE
Create Post has an error after image is taken and selected

### ISSUE THREAD

**Issue by richardpon** [TeamTravelJournal/AndroidTravelJournalApp#52]
Testing with commit d484ab7b5a8c631d37173a2a90c81a39256dc20a

From logcat:

06-13 12:00:22.415  14739-14739/com.mycompany.traveljournal E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mycompany.traveljournal, PID: 14739
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1034, result=-1, data=null} to activity {com.mycompany.traveljournal/com.mycompany.traveljournal.createscreen.CreatePostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mycompany.traveljournal.createscreen.CreatePostFragment.setPhotoPath(android.net.Uri)' on a null object reference
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3577)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3620)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mycompany.traveljournal.createscreen.CreatePostFragment.setPhotoPath(android.net.Uri)' on a null object reference
            at com.mycompany.traveljournal.createscreen.CreatePostActivity.onActivityResult(CreatePostActivity.java:54)
            at android.app.Activity.dispatchActivityResult(Activity.java:6192)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3573)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3620)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by richardpon** [comment]
This is caused to screen rotation. Currently, the screen has to be locked to portrait mode

**Comment by esrako** [comment]
Looked into issue. Able to reproduce the error this way: Rotate your screen during taking photo keep it rotated and make sure "screen rotation" setting on your phone is not locked.

Workaround: make sure "screen rotation" setting on your phone is locked, that way activity is not recreated in the middle of creating a post.

Solution: App to handle screen rotations. In our todo list.
